name: verify-blue-green

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install docker-compose (v2)
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose
          docker --version
          docker compose version

      - name: Start services
        env:
          BLUE_IMAGE: ${{ secrets.BLUE_IMAGE }}
          GREEN_IMAGE: ${{ secrets.GREEN_IMAGE }}
          ACTIVE_POOL: blue
          RELEASE_ID_BLUE: ci-blue
          RELEASE_ID_GREEN: ci-green
        run: |
          # copy env
          cat > .env <<EOF
          BLUE_IMAGE=${BLUE_IMAGE}
          GREEN_IMAGE=${GREEN_IMAGE}
          ACTIVE_POOL=${ACTIVE_POOL}
          RELEASE_ID_BLUE=${RELEASE_ID_BLUE}
          RELEASE_ID_GREEN=${RELEASE_ID_GREEN}
          BLUE_HOST_PORT=8081
          GREEN_HOST_PORT=8082
          NGINX_HOST_PORT=8080
          APP_PORT=3000
          EOF

          docker compose up -d --wait

      - name: Wait for services
        run: |
          sleep 5
          echo "Checking nginx..."
          curl -sSf http://localhost:8080/version || (docker compose logs nginx && exit 1)

      - name: Run failover tests
        run: |
          chmod +x ci/test_failover.sh
          ci/test_failover.sh
